# Pandas

In [41]:
!pip3 install pandas
!pip3 install pandas
import sys
!{sys.executable} -m ensurepip --upgrade
!{sys.executable} -m pip install pandas
import sys

print(sys.version)          # shows Python version
print(sys.path)             # shows all importable paths
print(sys.platform)         # tells OS (e.g., 'darwin' for macOS)
print(sys.argv)             # command line args (in scripts)


#openpyxl is a Python library used for:
#	•	Reading and writing Excel .xlsx files.
!pip3 install openpyxl

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Looking in links: /var/folders/73/8f3xzr29369gjrn1m6_qtjw80000gn/T/tmpg1eicxom
Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (25.1.1)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
3.13.2 (v3.13.2:4f8bb3947cf, Feb  4 2025, 11:51:10) [Clang 15.0.0 (clang-1500.3.9.4)]
['/Library/Frameworks/Python.framework/Versions/3.13/lib/python313.zip', '/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13', '/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/lib-dynload', '', '/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages']
darwin
['/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/ipykernel_launcher.py', '--f=/Users/user/Library/Jupyter/runtime/kernel-v371fe6ea087c7dd98010d620b4b91032a39bddc03.json']
Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openpyxl) (2.0.0)

# Testing Pandas is Running or Not

In [7]:
import pandas as pd

# Create test data using dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 22],
    'City': ['Kolkata', 'Mumbai', 'Delhi']
}

# Convert dictionary to DataFrame
df = pd.DataFrame(data)

# Show the DataFrame
print(df)

# Access a column
print("Names:\n", df['Name'])

# Filter rows where Age > 23
print("Age > 23:\n", df[df['Age'] > 23])

      Name  Age     City
0    Alice   25  Kolkata
1      Bob   30   Mumbai
2  Charlie   22    Delhi
Names:
 0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
Age > 23:
     Name  Age     City
0  Alice   25  Kolkata
1    Bob   30   Mumbai

In [24]:
import pandas as pd
df = pd.DataFrame(
    {
"Name": [
    "Braund , Mr. Owen Harris",
    "Allen, Mr. William Henry",
    "Bonnell, Miss. Elizabeth",
],
"Age": [
    22,
    35,
    58
],
"Sex": ["male", "male", "female"],

    })
df
df.head()  # Display the first few rows of the DataFrame
df.tail()  # Display the last few rows of the DataFrame
# df["Age"]

# df.info()



#When selecting a single column of a pandas DataFrame, the result is a pandas Series. To select the column, use the
#column label in between square brackets [].
ages = pd.Series([20, 10, 11], name="Age")
ages
df["Age"].max()  # Get the maximum age
df["Age"].min() # Get the minimum age
ages.max()  # Get the maximum ages from the Series

df.describe()  # Get a summary of statistics for the DataFrame

             Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000

# Titanic Data Set
Caution -> the Dataset of Titanic is Not toally clean atall ....

In [10]:
import pandas as pd
titanic = pd.read_csv("/Users/user/Desktop/Developer/jupyter/Pandas/Titanic-Dataset.csv")

titanic.columns = titanic.columns.str.strip().str.lower()  #	3.	.strip()
#➤ Removes unwanted leading and trailing spaces in the column names.
#Example: " Age " → "Age"
titanic["age"] = pd.to_numeric(titanic["age"], errors="coerce")  # Convert "Age" to numeric, Bhai errors="coerce" ka matlab hai : “Jo values number me convert nahi ho sakti, unhe NaN (Not a Number) bana do, taaki column numeric ban sake.”


# titanic.head()  # Display the first few rows of the Titanic dataset
titanic
titanic.head(8)

titanic.describe()  # Get a summary of statistics for the Titanic dataset
titanic.info()  # Get information about the DataFrame, including data types and non
titanic.tail()

#  The Titanic data as a spreadsheet.
titanic.to_excel("titanic.xlsx", sheet_name="passengers", index=False)
titanic = pd.read_excel("titanic.xlsx", sheet_name="passengers")
titanic.info()


# If i want to check ages among these passengers
ages = titanic["age"]
ages
ages.head()
titanic.dtypes # Display the data types of each column

type(titanic["age"]) # Check the type of the "Age" column    pandas.core.series.Series

titanic["age"].max()
titanic["age"].shape # Get the number of elements in the "Age" column (891,)




above_35 = titanic[titanic["age"]>35]
above_35.head()

titanic["age"] > 35


# print(titanic.index.tolist())
titanic["age"].head()
titanic[titanic["age"].isna()]  # Display rows where "Age" is NaN (missing values)
# if want to see the unknown passengers age then 
# titanic.rename(columns={"age": "Age"}, inplace=True)  # Rename the "age" column to "Age"

class_23 = titanic[titanic["pclass"].isin([2, 3])]  # Filter passengers in classes 2 and 3
print(class_23.head())
print(titanic['pclass'].unique())
# print(titanic.columns.tolist())

class_23 = titanic[(titanic["pclass"] == 2) | (titanic["pclass"] == 3)]
print(titanic["pclass"].unique())

age_no_na = titanic[titanic["age"].notna()]  # Filter rows where "Age" is not NaN
age_no_na.head()
# age_no_na.shape

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerid  891 non-null    int64
 1   survived     891 non-null    int64
 2   pclass       891 non-null    object
 3   name         891 non-null    object
 4   sex          891 non-null    object
 5   age          714 non-null    float64
 6   sibsp        891 non-null    int64
 7   parch        891 non-null    int64
 8   ticket       891 non-null    object
 9   fare         891 non-null    float64
 10  cabin        891 non-null    object
 11  embarked     891 non-null    object
dtypes: float64(2), int64(4), object(6)
memory usage: 90.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerid  891 non-null    int64
 1   survived     891 non-null    int64
 2   pclass       891 non-null    object
 3   name         891 non-null    object
 4   sex          891 non-null    object
 5   age          714 non-null    float64
 6   sibsp        891 non-null    int64
 7   parch        891 non-null    int64
 8   ticket       891 non-null    object
 9   fare         891 non-null    float64
 10  cabin        891 non-null    object
 11  embarked     891 non-null    object
dtypes: float64(2), int64(4), object(6)
memory usage: 83.7+ KB
Empty DataFrame
Columns: [passengerid, survived, pclass, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked]
Index: []
[' "Braund' ' "Cumings' ' "Heikkinen' ' "Futrelle' ' "Allen' ' "Moran'
 ' "McCarthy' ' "Palsson' ' "Johnson' ' "Nasser' ' "Sandstrom' ' "Bonnell'
 ' "Saundercock' ' "Andersson' ' "Vestrom' ' "Hewlett' ' "Rice'
 ' "Williams' ' "Vander Planke' ' "Masselmani' ' "Fynney' ' "Beesley'
 ' "McGowan' ' "Sloper' ' "Asplund' ' "Emir' ' "Fortune' ' "O\'Dwyer'
 ' "Todoroff' ' "Uruchurtu' ' "Spencer' ' "Glynn' ' "Wheadon' ' "Meyer'
 ' "Holverson' ' "Mamee' ' "Cann' ' "Nicola-Yarred' ' "Ahlin' ' "Turpin'
 ' "Kraeff' ' "Laroche' ' "Devaney' ' "Rogers' ' "Lennon' ' "O\'Driscoll'
 ' "Samaan' ' "Arnold-Franchi' ' "Panula' ' "Nosworthy' ' "Harper'
 ' "Faunthorpe' ' "Ostby' ' "Woolner' ' "Rugg' ' "Novel' ' "West'
 ' "Goodwin' ' "Sirayanian' ' "Icard' ' "Harris' ' "Skoog' ' "Stewart'
 ' "Moubarek' ' "Nye' ' "Crease' ' "Kink' ' "Jenkin' ' "Hood'
 ' "Chronopoulos' ' "Bing' ' "Moen' ' "Staneff' ' "Moutal' ' "Caldwell'
 ' "Dowdell' ' "Waelens' ' "Sheerlinck' ' "McDermott' ' "Carrau' ' "Ilett'
 ' "Backstrom' ' "Ford' ' "Slocovski' ' "Celotti' ' "Christmann'
 ' "Andreasson' ' "Chaffee' ' "Dean' ' "Coxon' ' "Shorney' ' "Goldschmidt'
 ' "Greenfield' ' "Doling' ' "Kantor' ' "Petranec' ' "Petroff' ' "White'
 ' "Johansson' ' "Gustafsson' ' "Mionoff' ' "Salkjelsvik' ' "Moss'
 ' "Rekic' ' "Porter' ' "Zabour' ' "Barton' ' "Jussila' ' "Attalah'
 ' "Pekoniemi' ' "Connors' ' "Baxter' ' "Hickman' ' "Moore' ' "Webber'
 ' "McMahon' ' "Madsen' ' "Peter' ' "Ekstrom' ' "Drazenoic' ' "Coelho'
 ' "Robins' ' "Weisz' ' "Sobey' ' "Richard' ' "Newsom' ' "Osen' ' "Giglio'
 ' "Boulos' ' "Nysten' ' "Hakkarainen' ' "Burke' ' "Andrew' ' "Nicholls'
 ' "Navratil' ' "Byles' ' "Bateman' ' "Pears' ' "Meo' ' "van Billiard'
 ' "Olsen' ' "Gilnagh' ' "Corn' ' "Smiljanic' ' "Sage' ' "Cribb' ' "Watt'
 ' "Bengtsson' ' "Calic' ' "Goldsmith' ' "Chibnall' ' "Baumann' ' "Ling'
 ' "Van der hoef' ' "Sivola' ' "Smith' ' "Klasen' ' "Lefebre' ' "Isham'
 ' "Hale' ' "Leonard' ' "Pernot' ' "Becker' ' "Kink-Heilmann' ' "Rood'
 ' "O\'Brien' ' "Romaine' ' "Bourke' ' "Turcin' ' "Pinsky' ' "Carbines'
 ' "Andersen-Jensen' ' "Brown' ' "Lurette' ' "Mernagh' ' "Madigan'
 ' "Yrois' ' "Vande Walle' ' "Johanson' ' "Youseff' ' "Cohen' ' "Strom'
 ' "Albimona' ' "Carr' ' "Blank' ' "Ali' ' "Cameron' ' "Perkin' ' "Givard'
 ' "Kiernan' ' "Newell' ' "Honkanen' ' "Jacobsohn' ' "Bazzani'
 ' "Sunderland' ' "Bracken' ' "Green' ' "Nenkoff' ' "Hoyt' ' "Berglund'
 ' "Mellors' ' "Lovell' ' "Fahlstrom' ' "Larsson' ' "Sjostedt' ' "Leyson'
 ' "Harknett' ' "Hold' ' "Collyer' ' "Pengelly' ' "Hunt' ' "Murphy'
 ' "Coleridge' ' "Maenpaa' ' "Minahan' ' "Lindahl' ' "Hamalainen'
 ' "Beckwith' ' "Carter' ' "Reed' ' "Stead' ' "Lobb' ' "Rosblom' ' "Touma'
 ' "Thorne' ' "Cherry' ' "Ward' ' "Parrish' ' "Taussig' ' "Harrison'
 ' "Henry' ' "Reeves' ' "Persson' ' "Graham' ' "Bissette' ' "Cairns'
 ' "Tornquist' ' "Mellinger' ' "Natsch' ' "Healy' ' "Andrews' ' "Lindblom'
 ' "Parkes' ' "Abbott' ' "Duane' ' "Olsson' ' "de Pelsmaeker' ' "Dorking'
 ' "Stankovic' ' "de Mulder' ' "Naidenoff' ' "Hosono' ' "Connolly'
 ' "Barber' ' "Bishop' ' "Levy' ' "Haas' ' "Mineff' ' "Lewy' ' "Hanna'
 ' "Allison' ' "Saalfeld' ' "Kelly' ' "McCoy' ' "Keane' ' "Fleming'
 ' "Penasco y Castellana' ' "Abelson' ' "Francatelli' ' "Hays' ' "Ryerson'
 ' "Lahtinen' ' "Hendekovic' ' "Hart' ' "Nilsson' ' "Moraweck' ' "Wick'
 ' "Spedden' ' "Dennis' ' "Danoff' ' "Slayter' ' "Young' ' "Nysveen'
 ' "Ball' ' "Hippach' ' "Partner' ' "Frauenthal' ' "Denkoff' ' "Burns'
 ' "Dahl' ' "Blackwell' ' "Collander' ' "Sedgwick' ' "Fox' ' "Davison'
 ' "Coutts' ' "Dimic' ' "Odahl' ' "Williams-Lambert' ' "Elias' ' "Yousif'
 ' "Vanden Steen' ' "Bowerman' ' "Funk' ' "McGovern' ' "Mockler'
 ' "del Carlo' ' "Barbara' ' "Asim' ' "Adahl' ' "Warren' ' "Moussa'
 ' "Jermyn' ' "Aubart' ' "Harder' ' "Wiklund' ' "Beavan' ' "Ringhini'
 ' "Landergren' ' "Widener' ' "Betros' ' "Bidois' ' "Nakid' ' "Tikkanen'
 ' "Plotcharsky' ' "Davies' ' "Buss' ' "Sadlier' ' "Lehmann' ' "Jansson'
 ' "McKane' ' "Pain' ' "Trout' ' "Niskanen' ' "Adams' ' "Oreskovic'
 ' "Gale' ' "Widegren' ' "Richards' ' "Birkeland' ' "Sdycoff'
 ' "Cunningham' ' "Sundman' ' "Meek' ' "Drew' ' "Silven' ' "Matthews'
 ' "Van Impe' ' "Gheorgheff' ' "Charters' ' "Zimmerman' ' "Danbom'
 ' "Wiseman' ' "Clarke' ' "Phillips' ' "Flynn' ' "Pickard'
 ' "Bjornstrom-Steffansson' ' "Thorneycroft' ' "Louch' ' "Kallio'
 ' "Silvey' ' "Kvillner' ' "Hampe' ' "Petterson' ' "Reynaldo'
 ' "Johannesen-Bratthammer' ' "Dodge' ' "Seward' ' "Baclini' ' "Peuchen'
 ' "Hagland' ' "Foreman' ' "Goldenberg' ' "Peduzzi' ' "Jalsevac'
 ' "Millet' ' "Kenyon' ' "Toomey' ' "O\'Connor' ' "Anderson' ' "Morley'
 ' "Gee' ' "Milling' ' "Maisner' ' "Goncalves' ' "Campbell' ' "Smart'
 ' "Scanlan' ' "Keefe' ' "Cacic' ' "Jerwan' ' "Strandberg' ' "Clifford'
 ' "Renouf' ' "Karlsson' ' "Hirvonen' ' "Frost' ' "Rouse' ' "Turkula'
 ' "Kent' ' "Somerton' ' "Windelov' ' "Molson' ' "Artagaveytia'
 ' "Stanley' ' "Yousseff' ' "Eustis' ' "Shellard' ' "Svensson' ' "Canavan'
 ' "O\'Sullivan' ' "Laitinen' ' "Maioni' ' "Quick' ' "Bradley' ' "Lang'
 ' "Daly' ' "McGough' ' "Rothschild' ' "Coleff' ' "Walker' ' "Lemore'
 ' "Ryan' ' "Angle' ' "Pavlovic' ' "Perreault' ' "Vovk' ' "Lahoud'
 ' "Kassem' ' "Farrell' ' "Ridsdale' ' "Farthing' ' "Salonen' ' "Hocking'
 ' "Toufik' ' "Butt' ' "LeRoy' ' "Risien' ' "Frolicher' ' "Crosby'
 ' "Beane' ' "Douglas' ' "Nicholson' ' "Padro y Manent' ' "Thayer'
 ' "Sharp' ' "Leeni' ' "Ohman' ' "Wright' ' "Duff Gordon' ' "Robbins'
 ' "de Messemaeker' ' "Morrow' ' "Sivic' ' "Norman' ' "Simmons'
 ' "Meanwell' ' "Stoytcheff' ' "Doharr' ' "Jonsson' ' "Appleton' ' "Rush'
 ' "Patchett' ' "Garside' ' "Caram' ' "Christy' ' "Downton' ' "Ross'
 ' "Paulner' ' "Jarvis' ' "Frolicher-Stehli' ' "Gilinski' ' "Murdlin'
 ' "Rintamaki' ' "Stephenson' ' "Elsbury' ' "Chapman' ' "Leitch'
 ' "Slabenoff' ' "Harrington' ' "Torber' ' "Homer' ' "Lindell' ' "Karaic'
 ' "Daniel' ' "Shutes' ' "Jardin' ' "Horgan' ' "Brocklebank' ' "Herman'
 ' "Gavey' ' "Yasbeck' ' "Kimball' ' "Hansen' ' "Bowen' ' "Sutton'
 ' "Kirkland' ' "Longley' ' "Bostandyeff' ' "O\'Connell' ' "Barkworth'
 ' "Lundahl' ' "Stahelin-Maeglin' ' "Parr' ' "Davis' ' "Leinonen'
 ' "Jensen' ' "Sagesser' ' "Foo' ' "Cor' ' "Simonius-Blumer' ' "Willey'
 ' "Mitkoff' ' "Kalvik' ' "O\'Leary' ' "Hegarty' ' "Radeff' ' "Eitemiller'
 ' "Badt' ' "Colley' ' "Lindqvist' ' "Butler' ' "Rommetvedt' ' "Cook'
 ' "Taylor' ' "Davidson' ' "Mitchell' ' "Wilhelms' ' "Watson'
 ' "Edvardsson' ' "Sawyer' ' "Turja' ' "Cardeza' ' "Peters' ' "Hassab'
 ' "Olsvigen' ' "Dakic' ' "Fischer' ' "Madill' ' "Dick' ' "Karun' ' "Lam'
 ' "Saad' ' "Weir' ' "Mullens' ' "Humblen' ' "Astor' ' "Silverthorne'
 ' "Gallagher' ' "Calderhead' ' "Cleaver' ' "Mayne' ' "Klaber'
 ' "Greenberg' ' "Soholt' ' "Endres' ' "Troutt' ' "McEvoy' ' "Gillespie'
 ' "Hodges' ' "Chambers' ' "Mannion' ' "Bryhl' ' "Ilmakangas' ' "Hassan'
 ' "Knight' ' "Berriman' ' "Troupiansky' ' "Lesurer' ' "Ivanoff'
 ' "Nankoff' ' "Hawksford' ' "Cavendish' ' "McNamee' ' "Stranden'
 ' "Sinkkonen' ' "Marvin' ' "Connaghton' ' "Wells' ' "Moor'
 ' "Vande Velde' ' "Jonkoff' ' "Carlsson' ' "Bailey' ' "Theobald'
 ' "Rothes' ' "Garfirth' ' "Nirva' ' "Barah' ' "Eklund' ' "Hogeboom'
 ' "Brewe' ' "Mangan' ' "Gronnestad' ' "Lievens' ' "Mack' ' "Myhrman'
 ' "Tobin' ' "Emanuel' ' "Kilgannon' ' "Robert' ' "Ayoub' ' "Long'
 ' "Johnston' ' "Harmer' ' "Sjoblom' ' "Guggenheim' ' "Gaskell'
 ' "Dantcheff' ' "Otter' ' "Leader' ' "Osman' ' "Ibrahim Shawah'
 ' "Ponesell' ' "Thomas' ' "Hedman' ' "Pettersson' ' "Alexander'
 ' "Lester' ' "Slemen' ' "Tomlin' ' "Fry' ' "Heininen' ' "Mallet' ' "Holm'
 ' "Lulic' ' "Reuchlin' ' "McCormack' ' "Stone' ' "Augustsson' ' "Allum'
 ' "Compton' ' "Pasic' ' "Sirota' ' "Chip' ' "Marechal' ' "Alhomaki'
 ' "Mudd' ' "Serepeca' ' "Lemberopolous' ' "Culumovic' ' "Abbing'
 ' "Markoff' ' "Lines' ' "Aks' ' "Razi' ' "Giles' ' "Swift' ' "Gill'
 ' "Bystrom' ' "Duran y More' ' "Roebling' ' "van Melkebeke' ' "Balkic'
 ' "Vander Cruyssen' ' "Najib' ' "Laleff' ' "Potter' ' "Shelley'
 ' "Markun' ' "Dahlberg' ' "Banfield' ' "Sutehall' ' "Montvila' ' "Behr'
 ' "Dooley']
[' "Braund' ' "Cumings' ' "Heikkinen' ' "Futrelle' ' "Allen' ' "Moran'
 ' "McCarthy' ' "Palsson' ' "Johnson' ' "Nasser' ' "Sandstrom' ' "Bonnell'
 ' "Saundercock' ' "Andersson' ' "Vestrom' ' "Hewlett' ' "Rice'
 ' "Williams' ' "Vander Planke' ' "Masselmani' ' "Fynney' ' "Beesley'
 ' "McGowan' ' "Sloper' ' "Asplund' ' "Emir' ' "Fortune' ' "O\'Dwyer'
 ' "Todoroff' ' "Uruchurtu' ' "Spencer' ' "Glynn' ' "Wheadon' ' "Meyer'
 ' "Holverson' ' "Mamee' ' "Cann' ' "Nicola-Yarred' ' "Ahlin' ' "Turpin'
 ' "Kraeff' ' "Laroche' ' "Devaney' ' "Rogers' ' "Lennon' ' "O\'Driscoll'
 ' "Samaan' ' "Arnold-Franchi' ' "Panula' ' "Nosworthy' ' "Harper'
 ' "Faunthorpe' ' "Ostby' ' "Woolner' ' "Rugg' ' "Novel' ' "West'
 ' "Goodwin' ' "Sirayanian' ' "Icard' ' "Harris' ' "Skoog' ' "Stewart'
 ' "Moubarek' ' "Nye' ' "Crease' ' "Kink' ' "Jenkin' ' "Hood'
 ' "Chronopoulos' ' "Bing' ' "Moen' ' "Staneff' ' "Moutal' ' "Caldwell'
 ' "Dowdell' ' "Waelens' ' "Sheerlinck' ' "McDermott' ' "Carrau' ' "Ilett'
 ' "Backstrom' ' "Ford' ' "Slocovski' ' "Celotti' ' "Christmann'
 ' "Andreasson' ' "Chaffee' ' "Dean' ' "Coxon' ' "Shorney' ' "Goldschmidt'
 ' "Greenfield' ' "Doling' ' "Kantor' ' "Petranec' ' "Petroff' ' "White'
 ' "Johansson' ' "Gustafsson' ' "Mionoff' ' "Salkjelsvik' ' "Moss'
 ' "Rekic' ' "Porter' ' "Zabour' ' "Barton' ' "Jussila' ' "Attalah'
 ' "Pekoniemi' ' "Connors' ' "Baxter' ' "Hickman' ' "Moore' ' "Webber'
 ' "McMahon' ' "Madsen' ' "Peter' ' "Ekstrom' ' "Drazenoic' ' "Coelho'
 ' "Robins' ' "Weisz' ' "Sobey' ' "Richard' ' "Newsom' ' "Osen' ' "Giglio'
 ' "Boulos' ' "Nysten' ' "Hakkarainen' ' "Burke' ' "Andrew' ' "Nicholls'
 ' "Navratil' ' "Byles' ' "Bateman' ' "Pears' ' "Meo' ' "van Billiard'
 ' "Olsen' ' "Gilnagh' ' "Corn' ' "Smiljanic' ' "Sage' ' "Cribb' ' "Watt'
 ' "Bengtsson' ' "Calic' ' "Goldsmith' ' "Chibnall' ' "Baumann' ' "Ling'
 ' "Van der hoef' ' "Sivola' ' "Smith' ' "Klasen' ' "Lefebre' ' "Isham'
 ' "Hale' ' "Leonard' ' "Pernot' ' "Becker' ' "Kink-Heilmann' ' "Rood'
 ' "O\'Brien' ' "Romaine' ' "Bourke' ' "Turcin' ' "Pinsky' ' "Carbines'
 ' "Andersen-Jensen' ' "Brown' ' "Lurette' ' "Mernagh' ' "Madigan'
 ' "Yrois' ' "Vande Walle' ' "Johanson' ' "Youseff' ' "Cohen' ' "Strom'
 ' "Albimona' ' "Carr' ' "Blank' ' "Ali' ' "Cameron' ' "Perkin' ' "Givard'
 ' "Kiernan' ' "Newell' ' "Honkanen' ' "Jacobsohn' ' "Bazzani'
 ' "Sunderland' ' "Bracken' ' "Green' ' "Nenkoff' ' "Hoyt' ' "Berglund'
 ' "Mellors' ' "Lovell' ' "Fahlstrom' ' "Larsson' ' "Sjostedt' ' "Leyson'
 ' "Harknett' ' "Hold' ' "Collyer' ' "Pengelly' ' "Hunt' ' "Murphy'
 ' "Coleridge' ' "Maenpaa' ' "Minahan' ' "Lindahl' ' "Hamalainen'
 ' "Beckwith' ' "Carter' ' "Reed' ' "Stead' ' "Lobb' ' "Rosblom' ' "Touma'
 ' "Thorne' ' "Cherry' ' "Ward' ' "Parrish' ' "Taussig' ' "Harrison'
 ' "Henry' ' "Reeves' ' "Persson' ' "Graham' ' "Bissette' ' "Cairns'
 ' "Tornquist' ' "Mellinger' ' "Natsch' ' "Healy' ' "Andrews' ' "Lindblom'
 ' "Parkes' ' "Abbott' ' "Duane' ' "Olsson' ' "de Pelsmaeker' ' "Dorking'
 ' "Stankovic' ' "de Mulder' ' "Naidenoff' ' "Hosono' ' "Connolly'
 ' "Barber' ' "Bishop' ' "Levy' ' "Haas' ' "Mineff' ' "Lewy' ' "Hanna'
 ' "Allison' ' "Saalfeld' ' "Kelly' ' "McCoy' ' "Keane' ' "Fleming'
 ' "Penasco y Castellana' ' "Abelson' ' "Francatelli' ' "Hays' ' "Ryerson'
 ' "Lahtinen' ' "Hendekovic' ' "Hart' ' "Nilsson' ' "Moraweck' ' "Wick'
 ' "Spedden' ' "Dennis' ' "Danoff' ' "Slayter' ' "Young' ' "Nysveen'
 ' "Ball' ' "Hippach' ' "Partner' ' "Frauenthal' ' "Denkoff' ' "Burns'
 ' "Dahl' ' "Blackwell' ' "Collander' ' "Sedgwick' ' "Fox' ' "Davison'
 ' "Coutts' ' "Dimic' ' "Odahl' ' "Williams-Lambert' ' "Elias' ' "Yousif'
 ' "Vanden Steen' ' "Bowerman' ' "Funk' ' "McGovern' ' "Mockler'
 ' "del Carlo' ' "Barbara' ' "Asim' ' "Adahl' ' "Warren' ' "Moussa'
 ' "Jermyn' ' "Aubart' ' "Harder' ' "Wiklund' ' "Beavan' ' "Ringhini'
 ' "Landergren' ' "Widener' ' "Betros' ' "Bidois' ' "Nakid' ' "Tikkanen'
 ' "Plotcharsky' ' "Davies' ' "Buss' ' "Sadlier' ' "Lehmann' ' "Jansson'
 ' "McKane' ' "Pain' ' "Trout' ' "Niskanen' ' "Adams' ' "Oreskovic'
 ' "Gale' ' "Widegren' ' "Richards' ' "Birkeland' ' "Sdycoff'
 ' "Cunningham' ' "Sundman' ' "Meek' ' "Drew' ' "Silven' ' "Matthews'
 ' "Van Impe' ' "Gheorgheff' ' "Charters' ' "Zimmerman' ' "Danbom'
 ' "Wiseman' ' "Clarke' ' "Phillips' ' "Flynn' ' "Pickard'
 ' "Bjornstrom-Steffansson' ' "Thorneycroft' ' "Louch' ' "Kallio'
 ' "Silvey' ' "Kvillner' ' "Hampe' ' "Petterson' ' "Reynaldo'
 ' "Johannesen-Bratthammer' ' "Dodge' ' "Seward' ' "Baclini' ' "Peuchen'
 ' "Hagland' ' "Foreman' ' "Goldenberg' ' "Peduzzi' ' "Jalsevac'
 ' "Millet' ' "Kenyon' ' "Toomey' ' "O\'Connor' ' "Anderson' ' "Morley'
 ' "Gee' ' "Milling' ' "Maisner' ' "Goncalves' ' "Campbell' ' "Smart'
 ' "Scanlan' ' "Keefe' ' "Cacic' ' "Jerwan' ' "Strandberg' ' "Clifford'
 ' "Renouf' ' "Karlsson' ' "Hirvonen' ' "Frost' ' "Rouse' ' "Turkula'
 ' "Kent' ' "Somerton' ' "Windelov' ' "Molson' ' "Artagaveytia'
 ' "Stanley' ' "Yousseff' ' "Eustis' ' "Shellard' ' "Svensson' ' "Canavan'
 ' "O\'Sullivan' ' "Laitinen' ' "Maioni' ' "Quick' ' "Bradley' ' "Lang'
 ' "Daly' ' "McGough' ' "Rothschild' ' "Coleff' ' "Walker' ' "Lemore'
 ' "Ryan' ' "Angle' ' "Pavlovic' ' "Perreault' ' "Vovk' ' "Lahoud'
 ' "Kassem' ' "Farrell' ' "Ridsdale' ' "Farthing' ' "Salonen' ' "Hocking'
 ' "Toufik' ' "Butt' ' "LeRoy' ' "Risien' ' "Frolicher' ' "Crosby'
 ' "Beane' ' "Douglas' ' "Nicholson' ' "Padro y Manent' ' "Thayer'
 ' "Sharp' ' "Leeni' ' "Ohman' ' "Wright' ' "Duff Gordon' ' "Robbins'
 ' "de Messemaeker' ' "Morrow' ' "Sivic' ' "Norman' ' "Simmons'
 ' "Meanwell' ' "Stoytcheff' ' "Doharr' ' "Jonsson' ' "Appleton' ' "Rush'
 ' "Patchett' ' "Garside' ' "Caram' ' "Christy' ' "Downton' ' "Ross'
 ' "Paulner' ' "Jarvis' ' "Frolicher-Stehli' ' "Gilinski' ' "Murdlin'
 ' "Rintamaki' ' "Stephenson' ' "Elsbury' ' "Chapman' ' "Leitch'
 ' "Slabenoff' ' "Harrington' ' "Torber' ' "Homer' ' "Lindell' ' "Karaic'
 ' "Daniel' ' "Shutes' ' "Jardin' ' "Horgan' ' "Brocklebank' ' "Herman'
 ' "Gavey' ' "Yasbeck' ' "Kimball' ' "Hansen' ' "Bowen' ' "Sutton'
 ' "Kirkland' ' "Longley' ' "Bostandyeff' ' "O\'Connell' ' "Barkworth'
 ' "Lundahl' ' "Stahelin-Maeglin' ' "Parr' ' "Davis' ' "Leinonen'
 ' "Jensen' ' "Sagesser' ' "Foo' ' "Cor' ' "Simonius-Blumer' ' "Willey'
 ' "Mitkoff' ' "Kalvik' ' "O\'Leary' ' "Hegarty' ' "Radeff' ' "Eitemiller'
 ' "Badt' ' "Colley' ' "Lindqvist' ' "Butler' ' "Rommetvedt' ' "Cook'
 ' "Taylor' ' "Davidson' ' "Mitchell' ' "Wilhelms' ' "Watson'
 ' "Edvardsson' ' "Sawyer' ' "Turja' ' "Cardeza' ' "Peters' ' "Hassab'
 ' "Olsvigen' ' "Dakic' ' "Fischer' ' "Madill' ' "Dick' ' "Karun' ' "Lam'
 ' "Saad' ' "Weir' ' "Mullens' ' "Humblen' ' "Astor' ' "Silverthorne'
 ' "Gallagher' ' "Calderhead' ' "Cleaver' ' "Mayne' ' "Klaber'
 ' "Greenberg' ' "Soholt' ' "Endres' ' "Troutt' ' "McEvoy' ' "Gillespie'
 ' "Hodges' ' "Chambers' ' "Mannion' ' "Bryhl' ' "Ilmakangas' ' "Hassan'
 ' "Knight' ' "Berriman' ' "Troupiansky' ' "Lesurer' ' "Ivanoff'
 ' "Nankoff' ' "Hawksford' ' "Cavendish' ' "McNamee' ' "Stranden'
 ' "Sinkkonen' ' "Marvin' ' "Connaghton' ' "Wells' ' "Moor'
 ' "Vande Velde' ' "Jonkoff' ' "Carlsson' ' "Bailey' ' "Theobald'
 ' "Rothes' ' "Garfirth' ' "Nirva' ' "Barah' ' "Eklund' ' "Hogeboom'
 ' "Brewe' ' "Mangan' ' "Gronnestad' ' "Lievens' ' "Mack' ' "Myhrman'
 ' "Tobin' ' "Emanuel' ' "Kilgannon' ' "Robert' ' "Ayoub' ' "Long'
 ' "Johnston' ' "Harmer' ' "Sjoblom' ' "Guggenheim' ' "Gaskell'
 ' "Dantcheff' ' "Otter' ' "Leader' ' "Osman' ' "Ibrahim Shawah'
 ' "Ponesell' ' "Thomas' ' "Hedman' ' "Pettersson' ' "Alexander'
 ' "Lester' ' "Slemen' ' "Tomlin' ' "Fry' ' "Heininen' ' "Mallet' ' "Holm'
 ' "Lulic' ' "Reuchlin' ' "McCormack' ' "Stone' ' "Augustsson' ' "Allum'
 ' "Compton' ' "Pasic' ' "Sirota' ' "Chip' ' "Marechal' ' "Alhomaki'
 ' "Mudd' ' "Serepeca' ' "Lemberopolous' ' "Culumovic' ' "Abbing'
 ' "Markoff' ' "Lines' ' "Aks' ' "Razi' ' "Giles' ' "Swift' ' "Gill'
 ' "Bystrom' ' "Duran y More' ' "Roebling' ' "van Melkebeke' ' "Balkic'
 ' "Vander Cruyssen' ' "Najib' ' "Laleff' ' "Potter' ' "Shelley'
 ' "Markun' ' "Dahlberg' ' "Banfield' ' "Sutehall' ' "Montvila' ' "Behr'
 ' "Dooley']

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,0,3,"""Braund","Mr. Owen Harris"" ...",male,22.0,1,0,A/5 21171,7.2500,,S
1,1,1,"""Cumings","Mrs. John Bradley (Florence Briggs Thayer)"" ...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"""Heikkinen","Miss. Laina"" ...",female,26.0,0,0,STON/O2. 3101282,7.9250,,S
3,1,1,"""Futrelle","Mrs. Jacques Heath (Lily May Peel)"" ...",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"""Allen","Mr. William Henry"" ...",male,35.0,0,0,373450,8.0500,,S